# Generated by Django 4.1.1 on 2022-09-30 02:13

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='propietario',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=50, verbose_name='Identificación')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('punto_de_partida', models.CharField(max_length=200, verbose_name='Punto de partida')),
                ('punto_de_llegada', models.CharField(max_length=200, verbose_name='Punto de llegada')),
                ('vehiculo', models.CharField(max_length=6, verbose_name='Placa')),
                ('valor', models.PositiveIntegerField(verbose_name='Valor')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado_solicitud', models.PositiveSmallIntegerField(choices=[(0, 'Cancelado'), (1, 'Pendiente'), (2, 'Confirmado'), (3, 'En transito'), (4, 'Finalizado')], default=0, verbose_name='Estado del viaje')),
            ],
            options={
                'verbose_name': 'solicitud viaje',
                'verbose_name_plural': 'solicitud viajes',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=6, verbose_name='Placa')),
                ('capacidad_de_pasajeros', models.PositiveSmallIntegerField(verbose_name='Capacidad de pasajeros')),
                ('cilindraje', models.CharField(max_length=50, verbose_name='Cilindraje')),
                ('fecha_SOAT', models.DateField(verbose_name='fecha de vigencia soat')),
                ('tarjeta_operacion', models.DateField(verbose_name='fecha de vigencia tarjeta de operacion')),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Deshabilitado'), (1, 'Habilitado')], verbose_name='Estado del vehiculo')),
                ('propietario', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='Transporte.propietario', verbose_name='identificacion del propietario')),
            ],
            options={
                'verbose_name': 'vehiculo',
                'verbose_name_plural': 'vehiculos',
                'ordering': ['placa'],
            },
        ),
    ]
