# Generated by Django 4.1.1 on 2022-10-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='km',
            field=models.FloatField(default=0, verbose_name='Kilometros'),
            preserve_default=False,
        ),
    ]
