# Generated by Django 4.1.1 on 2022-09-25 05:48

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=6, verbose_name='Placa')),
                ('capacidad_de_pasajeros', models.PositiveSmallIntegerField(verbose_name='Capacidad de pasajeros')),
                ('cilindraje', models.CharField(max_length=50, verbose_name='Cilindraje')),
                ('fecha_SOAT', models.DateField(verbose_name='fecha de vigencia soat')),
                ('propietario', models.CharField(max_length=20, verbose_name='identificacion del propietario')),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Deshabilitado'), (1, 'Habilitado')], verbose_name='Estado del vehiculo')),
            ],
            options={
                'verbose_name': 'vehiculo',
                'verbose_name_plural': 'vehiculos',
                'ordering': ['placa'],
            },
        ),
    ]
