# Generated by Django 4.1.1 on 2022-09-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tarjeta_operacion',
            field=models.DateField(default='2022-02-12', verbose_name='fecha de vigencia tarjeta de operacion'),
            preserve_default=False,
        ),
    ]
