#imagen
FROM python:3.8.3-alpine3.15

ENV PYTHONUNBUFFERED=1

#carpeta 
WORKDIR /app


RUN apk update\
    && apk add --no-cache gcc musl-dev postgresql-dev python3-dev libffi-dev\
    && pip instal --upgrade pip

COPY ./base.txt ./

RUN pip install -r base.txt

COPY ./ ./

CMD ["python", "manage.py", "runserver", "0.0.0.0:8002"]